KERNEL_VIDEO_WIDTH_pixel equ 640
KERNEL_VIDEO_HEIGHT_pixel equ 400
KERNEL_VIDEO_DEPTH_shift equ 2
KERNEL_VIDEO_DEPTH_byte equ 4
KERNEL_VIDEO_DEPTH_bit equ 32
KERNEL_VIDEO_SIZE_byte equ (KERNEL_VIDEO_WIDTH_pixel * KERNEL_VIDEO_HEIGHT_pixel) << KERNEL_VIDEO_DEPTH_shift

kernel_video_base_address dq STATIC_EMPTY
kernel_video_pointer dq STATIC_EMPTY
kernel_video_width_pixel dq STATIC_EMPTY
kernel_video_height_pixel dq STATIC_EMPTY

kernel_video_color_background dd 0x00141C21


kernel_video_cursor:
 .x: dd STATIC_EMPTY
 .y: dd STATIC_EMPTY

kernel_video_char_color_and_background db STATIC_COLOR_gray_light

kernel_video_color_sequence_default db STATIC_COLOR_ASCII_DEFAULT
kernel_video_color_sequence_black db STATIC_COLOR_ASCII_BLACK
kernel_video_color_sequence_blue db STATIC_COLOR_ASCII_BLUE
kernel_video_color_sequence_green db STATIC_COLOR_ASCII_GREEN
kernel_video_color_sequence_cyan db STATIC_COLOR_ASCII_CYAN
kernel_video_color_sequence_red db STATIC_COLOR_ASCII_RED
kernel_video_color_sequence_magenta db STATIC_COLOR_ASCII_MAGENTA
kernel_video_color_sequence_brown db STATIC_COLOR_ASCII_BROWN
kernel_video_color_sequence_gray_light db STATIC_COLOR_ASCII_GRAY_LIGHT
kernel_video_color_sequence_gray db STATIC_COLOR_ASCII_GRAY
kernel_video_color_sequence_blue_light db STATIC_COLOR_ASCII_BLUE_LIGHT
kernel_video_color_sequence_green_light db STATIC_COLOR_ASCII_GREEN_LIGHT
kernel_video_color_sequence_cyan_light db STATIC_COLOR_ASCII_CYAN_LIGHT
kernel_video_color_sequence_red_light db STATIC_COLOR_ASCII_RED_LIGHT
kernel_video_color_sequence_magenta_light db STATIC_COLOR_ASCII_MAGENTA_LIGHT
kernel_video_color_sequence_yellow db STATIC_COLOR_ASCII_YELLOW
kernel_video_color_sequence_white db STATIC_COLOR_ASCII_WHITE

kernel_video_drain:
 push rax
 push rcx
 push rdi

 mov eax, dword [kernel_video_color_background]
 mov ecx, KERNEL_VIDEO_WIDTH_pixel * KERNEL_VIDEO_HEIGHT_pixel
 mov rdi, qword [kernel_video_base_address]
 rep stosd

 mov qword [kernel_video_cursor], STATIC_EMPTY

 call kernel_video_cursor_set

 pop rdi
 pop rcx
 pop rax

 ret

kernel_video_cursor_set:

 ret

kernel_video_string:

 ret

kernel_video_char:

 ret


kernel_video_number:

 ret

kernel_video_scroll:

 ret
