
 ; constants, variables, globals, structures, objects, macros
 %include "software/header.asm"

 %define PROGRAM_NAME "tetris"
 %define PROGRAM_VERSION "0.1"

TETRIS_BRICK_START_POSITION_x equ 6
TETRIS_BRICK_START_POSITION_y equ 0

TETRIS_BRICK_STRUCTURE_width equ 4
TETRIS_BRICK_STRUCTURE_height equ 4

TETRIS_BRICK_PADDING_pixel equ 1
TETRIS_BRICK_WIDTH_pixel equ 6
TETRIS_BRICK_HEIGHT_pixel equ 6

TETRIS_PLAYGROUND_WIDTH_brick equ 10
TETRIS_PLAYGROUND_HEIGHT_brick equ 22
TETRIS_PLAYGROUND_HIDDEN_brick equ 2

TETRIS_PLAYGROUND_WIDTH_pixel equ TETRIS_PLAYGROUND_WIDTH_brick * (TETRIS_BRICK_WIDTH_pixel + TETRIS_BRICK_PADDING_pixel)
TETRIS_PLAYGROUND_HEIGHT_pixel equ (TETRIS_PLAYGROUND_HEIGHT_brick - TETRIS_PLAYGROUND_HIDDEN_brick) * (TETRIS_BRICK_HEIGHT_pixel + TETRIS_BRICK_PADDING_pixel)

TETRIS_WINDOW_WIDTH_pixel equ TETRIS_PLAYGROUND_WIDTH_pixel
TETRIS_WINDOW_HEIGHT_pixel equ TETRIS_PLAYGROUND_HEIGHT_pixel
